_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_toolbar: 0
  block: 0
  breakpoint: 0
  components: 0
  content_calendar: 0
  content_kanban: 0
  content_moderation: 0
  content_planner: 0
  ctools: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  field: 0
  file: 0
  filter: 0
  image: 0
  node: 0
  page_cache: 0
  path: 0
  path_alias: 0
  scheduler: 0
  system: 0
  text: 0
  token: 0
  toolbar: 0
  twig_temp: 0
  twig_tweak: 0
  update: 0
  user: 0
  workflows: 0
  pathauto: 1
  views: 10
  minimal: 1000
theme:
  stark: 0
profile: minimal
